spring.application.name=GodEcommerce
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username= # place your username here
spring.datasource.password= # place your password  here
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB
project.image=images/
jwt.secret= # place your jwt secret code here 
jwt.cookie.name=test  # use whatever name you want here
jwt.token.expiration=8h
spring.jpa.open-in-view=false
stripe.secret.key= # place your stripe secret key here
